#!/usr/bin/env python3
"""Run globally balanced pytest workers inside one existing CI shard."""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time
from collections.abc import Sequence
from pathlib import Path
from typing import Protocol, TextIO, cast

if not __package__:
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from scripts.ci.pytest_duration_manifest import (
    DURATION_REPORT_SCHEMA_VERSION,
    merge_duration_reports,
)

PLAN_SCHEMA_VERSION = 1
DEFAULT_WORKERS_PER_RUNNER = 4
DEFAULT_PLAN_BUDGET_SECONDS = 260.0
PREBUILT_DURATION_ENV = "GUARD_PYTEST_DURATION_PREBUILT"


class _Arguments(Protocol):
    plan: Path


def _valid_node_id(node_id: str) -> bool:
    return (
        node_id.startswith("tests/")
        and "\n" not in node_id
        and "\r" not in node_id
        and "\x00" not in node_id
    )


def write_parallel_plan(
    path: Path,
    *,
    root: Path,
    runner_index: int,
    runner_count: int,
    workers_per_runner: int,
    worker_nodes: Sequence[list[str]],
    planned_at_monotonic: float,
    budget_seconds: float = DEFAULT_PLAN_BUDGET_SECONDS,
) -> None:
    """Persist one runner's immutable worker plan for the outer pytest wrapper."""

    if runner_count < 1 or workers_per_runner < 1 or not 0 <= runner_index < runner_count:
        raise ValueError("parallel pytest plan coordinates are invalid")
    if len(worker_nodes) != workers_per_runner:
        raise ValueError("worker node plan does not match workers_per_runner")
    if planned_at_monotonic <= 0 or budget_seconds <= 0:
        raise ValueError("parallel pytest timing values must be positive")
    flattened = [node_id for shard in worker_nodes for node_id in shard]
    if (
        not flattened
        or len(flattened) != len(set(flattened))
        or not all(_valid_node_id(node_id) for node_id in flattened)
    ):
        raise ValueError("parallel pytest plan must contain unique valid test nodes")
    payload = {
        "schema_version": PLAN_SCHEMA_VERSION,
        "root": str(root.resolve(strict=True)),
        "runner_index": runner_index,
        "runner_count": runner_count,
        "workers_per_runner": workers_per_runner,
        "worker_nodes": [list(shard) for shard in worker_nodes],
        "planned_at_monotonic": planned_at_monotonic,
        "budget_seconds": budget_seconds,
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, sort_keys=True, indent=2) + "\n", encoding="utf-8")


def load_parallel_plan(path: Path) -> dict[str, object]:
    """Load and validate a plan generated by ``pytest_shard.py``."""

    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict) or payload.get("schema_version") != PLAN_SCHEMA_VERSION:
        raise ValueError("unsupported parallel pytest plan schema")
    root = payload.get("root")
    runner_index = payload.get("runner_index")
    runner_count = payload.get("runner_count")
    workers_per_runner = payload.get("workers_per_runner")
    worker_nodes = payload.get("worker_nodes")
    planned_at = payload.get("planned_at_monotonic")
    budget_seconds = payload.get("budget_seconds")
    if (
        not isinstance(root, str)
        or not isinstance(runner_index, int)
        or not isinstance(runner_count, int)
        or not isinstance(workers_per_runner, int)
        or not isinstance(worker_nodes, list)
        or not isinstance(planned_at, (int, float))
        or not isinstance(budget_seconds, (int, float))
    ):
        raise ValueError("parallel pytest plan fields are invalid")
    if runner_count < 1 or workers_per_runner < 1 or not 0 <= runner_index < runner_count:
        raise ValueError("parallel pytest plan coordinates are invalid")
    if planned_at <= 0 or budget_seconds <= 0:
        raise ValueError("parallel pytest timing values are invalid")
    normalized_nodes: list[list[str]] = []
    for shard in worker_nodes:
        if (
            not isinstance(shard, list)
            or not shard
            or not all(isinstance(node, str) and _valid_node_id(node) for node in shard)
        ):
            raise ValueError("parallel pytest plan contains an invalid worker shard")
        normalized_nodes.append(list(shard))
    if len(normalized_nodes) != workers_per_runner:
        raise ValueError("parallel pytest plan worker count is invalid")
    flattened = [node for shard in normalized_nodes for node in shard]
    if len(flattened) != len(set(flattened)):
        raise ValueError("parallel pytest plan contains duplicate test nodes")
    resolved_root = Path(root).resolve(strict=True)
    if not resolved_root.is_dir():
        raise ValueError("parallel pytest plan root is invalid")
    return {
        "root": resolved_root,
        "runner_index": runner_index,
        "runner_count": runner_count,
        "workers_per_runner": workers_per_runner,
        "worker_nodes": normalized_nodes,
        "planned_at_monotonic": float(planned_at),
        "budget_seconds": float(budget_seconds),
    }


def write_merged_duration_report(report_paths: Sequence[Path], output: Path) -> None:
    """Merge isolated worker reports into the existing per-runner artifact schema."""

    if not report_paths:
        raise ValueError("at least one pytest duration report is required")
    missing = [path for path in report_paths if not path.is_file()]
    if missing:
        rendered = ", ".join(str(path) for path in missing)
        raise FileNotFoundError(f"pytest workers did not produce duration reports: {rendered}")
    durations = merge_duration_reports(report_paths)
    output.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "schema_version": DURATION_REPORT_SCHEMA_VERSION,
        "node_durations_seconds": durations,
    }
    output.write_text(json.dumps(payload, sort_keys=True, indent=2) + "\n", encoding="utf-8")


def _worker_environment(root: Path, worker_dir: Path, report_path: Path, worker_id: int) -> dict[str, str]:
    environment = os.environ.copy()
    home = worker_dir / "home"
    temporary = worker_dir / "tmp"
    xdg_cache = worker_dir / "xdg-cache"
    xdg_config = worker_dir / "xdg-config"
    xdg_data = worker_dir / "xdg-data"
    xdg_state = worker_dir / "xdg-state"
    for directory in (home, temporary, xdg_cache, xdg_config, xdg_data, xdg_state):
        directory.mkdir(parents=True, exist_ok=True)

    existing_pythonpath = environment.get("PYTHONPATH")
    pythonpath_parts = [str(root / "scripts" / "ci")]
    if existing_pythonpath:
        pythonpath_parts.append(existing_pythonpath)
    environment.update(
        {
            "GUARD_CI_WORKER_ID": str(worker_id),
            "GUARD_PYTEST_DURATION_OUTPUT": str(report_path),
            "HOME": str(home),
            "USERPROFILE": str(home),
            "TMPDIR": str(temporary),
            "TMP": str(temporary),
            "TEMP": str(temporary),
            "XDG_CACHE_HOME": str(xdg_cache),
            "XDG_CONFIG_HOME": str(xdg_config),
            "XDG_DATA_HOME": str(xdg_data),
            "XDG_STATE_HOME": str(xdg_state),
            "PYTHONHASHSEED": "0",
            "PYTHONPATH": os.pathsep.join(pythonpath_parts),
        }
    )
    environment.pop(PREBUILT_DURATION_ENV, None)
    return environment


def _start_worker(
    *,
    root: Path,
    work_dir: Path,
    local_index: int,
    global_index: int,
    node_ids: list[str],
) -> tuple[subprocess.Popen[bytes], TextIO, Path, Path]:
    worker_dir = work_dir / f"worker-{local_index}"
    worker_dir.mkdir(parents=True, exist_ok=True)
    node_file = worker_dir / "pytest-nodes.txt"
    report_path = worker_dir / "pytest-durations.json"
    log_path = worker_dir / "pytest.log"
    basetemp = worker_dir / "pytest-tmp"
    cache_dir = worker_dir / "pytest-cache"
    node_file.write_text("\n".join(node_ids) + "\n", encoding="utf-8")
    log_handle = log_path.open("w", encoding="utf-8")
    command = [
        sys.executable,
        "-m",
        "pytest",
        "-p",
        "pytest_duration_report",
        f"@{node_file}",
        "--tb=short",
        f"--basetemp={basetemp}",
        "-o",
        f"cache_dir={cache_dir}",
    ]
    process = subprocess.Popen(
        command,
        cwd=root,
        env=_worker_environment(root, worker_dir, report_path, global_index),
        stdin=subprocess.DEVNULL,
        stdout=log_handle,
        stderr=subprocess.STDOUT,
    )
    return process, log_handle, log_path, report_path


def _print_worker_log(local_index: int, global_index: int, log_path: Path) -> None:
    print(f"::group::pytest worker {local_index} (global shard {global_index})")
    try:
        print(log_path.read_text(encoding="utf-8"), end="")
    except OSError as exc:
        print(f"unable to read pytest worker log: {exc}", file=sys.stderr)
    print("::endgroup::")


def run_pytest_workers(
    *,
    root: Path,
    work_dir: Path,
    runner_index: int,
    workers_per_runner: int,
    worker_nodes: Sequence[list[str]],
) -> tuple[list[int], list[Path]]:
    """Execute isolated pytest subprocesses and return exit codes plus report paths."""

    if len(worker_nodes) != workers_per_runner:
        raise ValueError("worker node plan does not match workers_per_runner")
    work_dir.mkdir(parents=True, exist_ok=True)
    running: list[tuple[int, int, subprocess.Popen[bytes], TextIO, Path, Path]] = []
    for local_index, node_ids in enumerate(worker_nodes):
        global_index = runner_index * workers_per_runner + local_index
        process, log_handle, log_path, report_path = _start_worker(
            root=root,
            work_dir=work_dir,
            local_index=local_index,
            global_index=global_index,
            node_ids=node_ids,
        )
        running.append((local_index, global_index, process, log_handle, log_path, report_path))
        print(
            f"started pytest worker {local_index} as global shard {global_index} "
            f"with {len(node_ids)} test nodes",
            flush=True,
        )

    last_heartbeat = time.monotonic()
    while any(process.poll() is None for _, _, process, _, _, _ in running):
        time.sleep(2)
        now = time.monotonic()
        if now - last_heartbeat >= 20:
            active = [
                str(global_index)
                for _, global_index, process, _, _, _ in running
                if process.poll() is None
            ]
            print(f"pytest workers still running: {', '.join(active)}", flush=True)
            last_heartbeat = now

    exit_codes: list[int] = []
    report_paths: list[Path] = []
    for local_index, global_index, process, log_handle, log_path, report_path in running:
        log_handle.close()
        return_code = process.wait()
        exit_codes.append(return_code)
        report_paths.append(report_path)
        _print_worker_log(local_index, global_index, log_path)
    return exit_codes, report_paths


def run_parallel_plan(plan_path: Path) -> None:
    """Run one generated plan from the outer pytest wrapper test."""

    plan = load_parallel_plan(plan_path)
    root = cast(Path, plan["root"])
    runner_index = cast(int, plan["runner_index"])
    workers_per_runner = cast(int, plan["workers_per_runner"])
    worker_nodes = cast(list[list[str]], plan["worker_nodes"])
    planned_at = cast(float, plan["planned_at_monotonic"])
    budget_seconds = cast(float, plan["budget_seconds"])
    output_value = os.environ.get("GUARD_PYTEST_DURATION_OUTPUT")
    if not output_value:
        raise RuntimeError("GUARD_PYTEST_DURATION_OUTPUT is required for parallel CI")
    output = Path(output_value)
    os.environ[PREBUILT_DURATION_ENV] = "1"
    exit_codes, report_paths = run_pytest_workers(
        root=root,
        work_dir=plan_path.parent / "workers",
        runner_index=runner_index,
        workers_per_runner=workers_per_runner,
        worker_nodes=worker_nodes,
    )
    write_merged_duration_report(report_paths, output)
    failed = [index for index, return_code in enumerate(exit_codes) if return_code != 0]
    if failed:
        rendered = ", ".join(str(index) for index in failed)
        raise AssertionError(f"pytest workers failed: {rendered}")
    elapsed = time.monotonic() - planned_at
    print(f"parallel pytest shard completed in {elapsed:.1f}s (budget {budget_seconds:.1f}s)")
    if elapsed >= budget_seconds:
        raise AssertionError(
            f"parallel pytest shard exceeded the {budget_seconds:.1f}s interactive CI budget: {elapsed:.1f}s"
        )


def main() -> int:
    parser = argparse.ArgumentParser()
    _ = parser.add_argument("--plan", type=Path, required=True)
    args = cast(_Arguments, cast(object, parser.parse_args()))
    run_parallel_plan(args.plan)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
