from pathlib import Path

path = Path("rust/crates/guard-hook-core/src/lib.rs")
text = path.read_text(encoding="utf-8")
old_import = "use guard_secure_fs::{read_bounded, resolve_candidate, sensitive_path_family, source_like, SecureReadError};"
new_import = "use guard_secure_fs::{classify_source_path, read_bounded, sensitive_path_family, SecureReadError};"
if text.count(old_import) != 1:
    raise RuntimeError("guard-secure-fs import anchor changed")
text = text.replace(old_import, new_import, 1)
old_block = '''    let candidate = source.tool_input_path.as_deref().unwrap_or(&source.path);\n    if candidate != target {\n        return HookReviewResponseV1::deny("source_ref_target_mismatch", "HOL Guard could not complete local hook review safely.");\n    }\n    let cwd = request.cwd.as_deref().map(Path::new);\n    let home = Path::new(&request.home_dir);\n    let path = match resolve_candidate(candidate, cwd, home) {\n        Ok(path) => path,\n        Err(_) => return HookReviewResponseV1::deny("unresolved_path", "HOL Guard could not complete local hook review safely."),\n    };\n    if let Some((family, _)) = sensitive_path_family(&path) {\n        return HookReviewResponseV1::deny("sensitive_path", sensitive_reason(family));\n    }\n    if !source_like(&path) {\n        return HookReviewResponseV1::deny("not_source_like", "HOL Guard could not complete local hook review safely.");\n    }\n'''
new_block = '''    let candidate = source.tool_input_path.as_deref().unwrap_or(&source.path);\n    let cwd = request.cwd.as_deref().map(Path::new).unwrap_or_else(|| Path::new("."));\n    let home = Path::new(&request.home_dir);\n    if let Some((family, _)) = sensitive_path_family(Path::new(candidate)) {\n        return HookReviewResponseV1::deny("sensitive_path", sensitive_reason(family));\n    }\n    let allow_external = matches!(request.harness.as_str(), "pi" | "omp") && request.source_ref_external_allowed;\n    let candidate_decision = classify_source_path(candidate, cwd, Some(home), allow_external);\n    if !candidate_decision.allowed {\n        return HookReviewResponseV1::deny(candidate_decision.reason_code, "HOL Guard could not complete local hook review safely.");\n    }\n    let target_decision = classify_source_path(&target, cwd, Some(home), allow_external);\n    if !target_decision.allowed {\n        return HookReviewResponseV1::deny("unresolved_envelope_target", "HOL Guard could not complete local hook review safely.");\n    }\n    let Some(path) = candidate_decision.resolved_path else {\n        return HookReviewResponseV1::deny("unresolved_path", "HOL Guard could not complete local hook review safely.");\n    };\n    let Some(target_path) = target_decision.resolved_path else {\n        return HookReviewResponseV1::deny("unresolved_envelope_target", "HOL Guard could not complete local hook review safely.");\n    };\n    if path != target_path {\n        return HookReviewResponseV1::deny("source_ref_target_mismatch", "HOL Guard could not complete local hook review safely.");\n    }\n'''
if text.count(old_block) != 1:
    raise RuntimeError("review_source path anchor changed")
text = text.replace(old_block, new_block, 1)
path.write_text(text, encoding="utf-8")
