"""Refresh stale harness launcher shims after a Guard package upgrade.

``install_guard_shim()`` only runs on explicit protect/install flows, so a
user who upgrades the Guard package keeps launcher shims generated by the
old version until they reinstall protection. The daemon startup path calls
:func:`refresh_stale_harness_shims` to regenerate any shim whose on-disk
content no longer matches the current generator output.

Workspace-scoped installs are preserved: the expected shim body is rebuilt
with the workspace recorded in the store's managed-installs table, so a
refresh never strips a ``--workspace`` binding from an existing shim.

The refresh is content-addressed: shims that already match the current
generator are left untouched, so steady-state startup cost is one file read
per installed shim.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING

from .shims import HarnessContextLike, _build_python_shim

if TYPE_CHECKING:
    from collections.abc import Mapping


@dataclass(frozen=True, slots=True)
class ShimRefreshResult:
    refreshed: tuple[str, ...]
    unchanged: tuple[str, ...]
    errors: tuple[str, ...]


class _RefreshContext:
    """HarnessContextLike for shim regeneration at daemon startup."""

    def __init__(self, home_dir: Path, guard_home: Path, workspace_dir: Path | None) -> None:
        self.home_dir = home_dir
        self.workspace_dir = workspace_dir
        self.guard_home = guard_home
        self.home_override_explicit = False


def _launcher_map() -> dict[str, tuple[str, str]]:
    """Map on-disk shim names to (harness, launcher_name) via adapter metadata.

    Shim filenames are launcher names, not harness names: e.g. guard-claude is
    the claude-code harness, guard-cursor-agent is cursor. Both the active
    launcher name and any legacy names map to the same adapter so upgrades
    rewrite whichever name is on disk to the current canonical launcher.
    """

    from .adapters import list_adapters

    mapping: dict[str, tuple[str, str]] = {}
    for adapter in list_adapters():
        launcher_name = getattr(adapter, "launcher_name", "") or adapter.harness
        mapping.setdefault(launcher_name, (adapter.harness, launcher_name))
        for legacy_name in getattr(adapter, "legacy_launcher_names", ()):
            mapping.setdefault(legacy_name, (adapter.harness, launcher_name))
    return mapping


def _existing_shim_harnesses(shim_dir: Path) -> list[str]:
    """Return launcher names with an installed Guard launcher shim."""

    if not shim_dir.is_dir():
        return []
    results: list[str] = []
    for entry in sorted(shim_dir.iterdir()):
        if not entry.name.startswith("guard-") or entry.name.endswith(".cmd"):
            continue
        if not entry.is_file():
            continue
        results.append(entry.name[len("guard-"):])
    return results


def _workspace_dir_from_install(install: Mapping[str, object] | None) -> Path | None:
    if install is None:
        return None
    workspace = install.get("workspace")
    if not isinstance(workspace, str) or not workspace.strip():
        return None
    return Path(workspace)


def refresh_stale_harness_shims(
    *,
    home_dir: Path,
    guard_home: Path,
    managed_installs: list[Mapping[str, object]] | None = None,
) -> ShimRefreshResult:
    """Regenerate harness shims whose content predates the current generator.

    ``managed_installs`` supplies workspace bindings from the store so
    refreshed shims keep their original ``--workspace`` arguments. Only the
    POSIX shim body is compared; the Windows ``.cmd`` companion forwards to
    the POSIX path and is rewritten by ``install_guard_shim`` alongside it,
    keeping both platforms in lockstep after upgrades.
    """

    shim_dir = guard_home / "bin"
    launcher_names = _existing_shim_harnesses(shim_dir)
    if not launcher_names:
        return ShimRefreshResult(refreshed=(), unchanged=(), errors=())
    launcher_map = _launcher_map()
    installs_by_harness = {
        str(install.get("harness")): install for install in (managed_installs or [])
    }
    # Imported lazily so daemon startup cost stays on this path.
    from .shims import install_guard_shim

    refreshed: list[str] = []
    unchanged: list[str] = []
    errors: list[str] = []
    for shim_name in launcher_names:
        posix_path = shim_dir / f"guard-{shim_name}"
        resolved = launcher_map.get(shim_name)
        if resolved is None:
            # Shim for a harness this package version no longer knows; leave it.
            unchanged.append(shim_name)
            continue
        harness, canonical_launcher = resolved
        try:
            install = installs_by_harness.get(harness)
            workspace_dir = _workspace_dir_from_install(install)
            context: HarnessContextLike = _RefreshContext(home_dir, guard_home, workspace_dir)
            workspace_args = ["--workspace", str(workspace_dir)] if workspace_dir is not None else []
            expected = _build_python_shim(harness, context, workspace_args)
            try:
                current = posix_path.read_text(encoding="utf-8")
            except OSError as error:
                errors.append(f"{shim_name}: read failed: {error}")
                continue
            stale_content = current != expected
            legacy_name = shim_name != canonical_launcher
            if not stale_content and not legacy_name:
                unchanged.append(shim_name)
                continue
            install_guard_shim(harness, context, launcher_name=canonical_launcher)
            if legacy_name:
                # install_guard_shim writes only the canonical name; remove the
                # legacy launcher (and its .cmd companion) so the refresh is
                # one-shot instead of re-firing on every daemon start.
                for suffix in ("", ".cmd"):
                    legacy_path = shim_dir / f"guard-{shim_name}{suffix}"
                    try:
                        legacy_path.unlink(missing_ok=True)
                    except OSError as error:
                        errors.append(f"{shim_name}: legacy unlink failed: {error}")
            refreshed.append(shim_name)
        except Exception as error:
            errors.append(f"{shim_name}: {error}")
    return ShimRefreshResult(refreshed=tuple(refreshed), unchanged=tuple(unchanged), errors=tuple(errors))


__all__ = ["ShimRefreshResult", "refresh_stale_harness_shims"]
